@baseUrl = http://localhost:5000/api

### 1. Register User (Hanya sekali saja)
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
    "username": "admin",
    "password": "admin",
    "full_name": "Administrator",
    "user_group_id": 1
}

### 2. Login (Lakukan ini untuk dapat TOKEN)
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    # "username": "admin",
    # "password": "admin"
    "username": "kiero_admin",
    "password": "password123"
}

### SIMPAN TOKEN DARI HASIL LOGIN DI ATAS DISINI:
@token = {{login.response.body.token}}

### 3. Ambil Data Barang (Pakai Token)
# Jika token benar, data muncul. Jika salah/tanpa token, error 401.
GET {{baseUrl}}/barang
Authorization: Bearer {{token}}

### 4. Logout
POST {{baseUrl}}/auth/logout