// constants.js
export const ROLES = {
  ADMIN: 1,
  MANAGER: 2,
  STAFF: 3,
};

// Buat "Grup Izin" yang dinamis
export const PERMISSIONS = {
  // CAN_EDIT_USER: [ROLES.ADMIN, ROLES.MANAGER],
  // CAN_DELETE_BARANG: [ROLES.ADMIN, ROLES.MANAGER],
  // CAN_VIEW_REPORT: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF],
  CAN_ADD_USER: [ROLES.ADMIN, ROLES.MANAGER],
  CAN_EDIT_USER: [ROLES.ADMIN, ROLES.MANAGER],
  CAN_DELETE_USER: [ROLES.ADMIN, ROLES.MANAGER],

  CAN_ADD_BARANG: [ROLES.ADMIN, ROLES.MANAGER],
  CAN_EDIT_BARANG: [ROLES.ADMIN, ROLES.MANAGER],
  CAN_DELETE_BARANG: [ROLES.ADMIN, ROLES.MANAGER],

  CAN_VIEW_REPORT: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF],
};
